# WuBu Configuration File
# This file contains example configurations for WuBu subsystems.

# General WuBu Settings
wubu_name: "WuBu"
profile: "default"

# TTS (Text-to-Speech) Configuration
tts:
  default_voice: "zonos_engine_local_cloning" # Default to local Zonos engine
  estimated_max_speech_duration: 7

  # Configuration for ZonosLocalVoice (Local Zonos, high-quality, voice cloning)
  # Requires successful setup of Zonos dependencies (Python packages, eSpeak-NG, CUDA if using GPU).
  zonos_local_engine:
    enabled: true # Set to true to enable Local Zonos TTS
    language: 'en' # Default language for Zonos (e.g., "en", "ja", "zh", "fr", "de")
    model_id: "Zyphra/Zonos-v0.1-transformer" # Hugging Face model ID or local path
    device: "cpu" # Change to "cuda" for GPU acceleration if available and configured.
                   # Ensure CUDA environment (e.g., CUDA 12.4 for Zonos) is correctly set up.
    default_reference_audio_path: "" # Optional: e.g., "assets/voices/my_local_speaker.wav"
    # unconditional_keys: ["emotion"] # Default in ZonosLocalVoice
    # cfg_scale: 2.0
    # sampling_params:
    #   min_p: 0.1

  # Configuration for WubuGLaDOSStyleVoice (Coqui XTTSv2 based characteristic voice)
  # To use this, set default_voice: "WuBu-GLaDOS-Style" and ensure enabled: true
  wubu_glados_style_voice:
    enabled: false # Disabled by default if Zonos is the primary
    language: 'en'
    model_subdir: 'glados_tts_models'
    speaker_wav_filename: 'glados_reference.wav'
    use_gpu: true

  # Configuration for WubuKokoroVoice (Standard/Neutral voice)
  # To use this, set default_voice: "WuBu-Kokoro" and ensure enabled: true
  wubu_kokoro_voice:
    enabled: false # Disabled by default if Zonos is the primary
    engine_type: 'coqui'
    language: 'en'
    coqui_model_name: "tts_models/en/ljspeech/tacotron2-DDC"
    use_gpu: true

# ASR (Automatic Speech Recognition) Configuration
asr:
  enabled: false # Keep disabled unless explicitly requested
  engine: "vosk"
  vosk_model_path: "asr_models/vosk-model-small-en-us-0.15"
  vosk_sample_rate: 16000
  audio_input_device_index: null
  silence_threshold: 1.0

# LLM (Large Language Model) Configuration
llm:
  provider: "ollama"
  ollama_settings:
    model: "qwen2.5-coder:7b-instruct-q4_K_M" # Set to user's preferred model
    host: "http://localhost:11434"
    # request_timeout: 60

# Vision Subsystem Configuration (Moondream v2 is used via desktop_tools/moondream_interaction.py, not directly configured here usually)
vision:
  enabled: false # General vision subsystem toggle, specific tools like moondream might operate independently if called.

# Desktop Tools Configuration
desktop_tools:
  enabled: true

# Logging Configuration
logging:
  level: "INFO"
  log_file: "wubu.log"
  max_log_size_mb: 10
  backup_count: 3
